parameters:
#    fbr_vote.example.class: Dp\FbrVoteBundle\Example

services:
#    fbr_vote.example:
#        class: %fbr_vote.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
