<?php

namespace Dp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends EntityRepository
{
    public function getOneByNameWithoutAccent($name){

        $qb = $this->createQueryBuilder('c')
                   ->where('UPPER(c.name) = :name')
                   ->setParameter('name', $name);

        return $qb->getQuery()->getOneOrNullResult();

    }
}
