<?php

namespace Dp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DofusdbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DofusdbookRepository extends EntityRepository
{
    /**
     * Retourne un item avec ses characteristics
     * @param $arrayId de type array(1=> id, 2=> id);
     * @return results
     */
    public function findByDbId($arrayId)
    {
        $qb = $this->createQueryBuilder('d')
                   ->where('d.dbookId IN (:id)')
                   ->setParameter('id', $arrayId);

        return $qb->getQuery()->getResult();
    }
}
