<?php

namespace Dp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    /**
     * Retourne un item avec ses caracteristiques
     * @param $id
     * @return results
     */
    public function findOneItemWithCharacteristics($id)
    {
        $qb = $this->createQueryBuilder('i')
                   ->join('i.effects', 'e')
                   ->addSelect('e')
                   ->where('i.id = :id')
                   ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }

    public function findItemListByItemtypeId($itemtypeId, $minlvl, $maxlvl)
    {
        $qb = $this->createQueryBuilder('i')
                   ->where('i.itemtype = :id')
                   ->andWhere('i.lvl BETWEEN :minlvl AND :maxlvl')
                   ->setParameter('id', $itemtypeId)
                   ->setParameter('minlvl', $minlvl)
                   ->setParameter('maxlvl', $maxlvl);

        return $qb->getQuery()->getResult();
    }
}
