<?php

namespace Dp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemtypeRepository extends EntityRepository
{
}
