<?php

namespace Dp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StuffdetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StuffdetailRepository extends EntityRepository
{

    public function findAllCharacteristicsByStuff($stuffId){
        return  $this->createQueryBuilder('sd')
                     ->leftJoin('sd.item', 'i')
                     ->leftJoin('i.effects', 'c1')
                     ->leftJoin('c1.effecttype', 'ct1')       
                     ->addSelect('i')
                     ->addSelect('c1')
                     ->addSelect('ct1')
                     ->where('sd.stuff = :req')
                     ->setParameter('req', $stuffId)
                     ->getQuery()
                     ->getResult();
    }
}
